version: "3.9"
services:
  db:
    image: postgres:17
    container_name: postgres17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./Backend
    container_name: backend
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      LOG_DIR: ${LOG_DIR}

    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - ./Backend:/app

  frontend:
    build: ./Frontend
    container_name: frontend
    restart: always
    env_file:
      - .env
    environment:
      VITE_APP_API_URL: ${VITE_APP_API_URL}
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
